// server/db.ts - In-memory store with realistic seed data for Mess Management System
import type {
  Candidate,
  Attendance,
  Meal,
  Expense,
  StockItem,
  StockTransaction,
  Staff,
  StaffPayment,
  StaffAdvance,
  FeeCollection,
  Party,
  Menu,
} from '../src/types';

// Helper for generating IDs
let idCounter = 100;
export const uid = (prefix = 'id') => `${prefix}_${Date.now()}_${++idCounter}`;

const todayStr = new Date().toISOString().split('T')[0];
const currentMonth = new Date().getMonth() + 1;
const currentYear = new Date().getFullYear();

// Seed Candidates
export let candidates: Candidate[] = [
  {
    id: 'cand_1',
    candidateId: 'CAND-001',
    fullName: 'Rahul Sharma',
    phoneNumber: '+91 98765 43210',
    email: 'rahul.s@example.com',
    address: 'Room 204, Ganga Hostel, Campus',
    joiningDate: '2025-01-10',
    monthlyRate: 3500,
    status: 'ACTIVE',
    emergencyContact: 'Mr. R. K. Sharma (Father)',
    emergencyPhone: '+91 98765 00001',
    notes: 'Pure vegetarian, lactose sensitive',
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'cand_2',
    candidateId: 'CAND-002',
    fullName: 'Aarav Patel',
    phoneNumber: '+91 98234 56789',
    email: 'aarav.p@example.com',
    address: 'Room 102, Yamuna Hostel, Campus',
    joiningDate: '2025-02-01',
    monthlyRate: 3500,
    status: 'ACTIVE',
    emergencyContact: 'Smt. Geeta Patel (Mother)',
    emergencyPhone: '+91 98234 00002',
    notes: 'Regular plan with weekend non-veg',
    createdAt: '2025-02-01T09:30:00Z',
    updatedAt: '2025-02-01T09:30:00Z',
  },
  {
    id: 'cand_3',
    candidateId: 'CAND-003',
    fullName: 'Priya Iyer',
    phoneNumber: '+91 97123 45678',
    email: 'priya.iyer@example.com',
    address: 'Room 305, Saraswati Block',
    joiningDate: '2025-01-15',
    monthlyRate: 3500,
    status: 'ACTIVE',
    emergencyContact: 'Venkatesh Iyer (Father)',
    emergencyPhone: '+91 97123 00003',
    notes: 'South Indian preferences, Jain on Thursdays',
    createdAt: '2025-01-15T11:00:00Z',
    updatedAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'cand_4',
    candidateId: 'CAND-004',
    fullName: 'Vikram Singh',
    phoneNumber: '+91 99887 76655',
    email: 'vikram.singh@example.com',
    address: 'Room 110, Ganga Hostel',
    joiningDate: '2025-01-05',
    monthlyRate: 3800,
    status: 'ACTIVE',
    emergencyContact: 'Balwinder Singh (Father)',
    emergencyPhone: '+91 99887 00004',
    notes: 'Heavy gym diet, extra eggs/milk addon',
    createdAt: '2025-01-05T08:00:00Z',
    updatedAt: '2025-01-05T08:00:00Z',
  },
  {
    id: 'cand_5',
    candidateId: 'CAND-005',
    fullName: 'Ananya Deshmukh',
    phoneNumber: '+91 98450 11223',
    email: 'ananya.d@example.com',
    address: 'Room 401, Godavari Block',
    joiningDate: '2024-08-01',
    leavingDate: '2025-01-31',
    monthlyRate: 3500,
    status: 'LEFT',
    emergencyContact: 'Manoj Deshmukh (Father)',
    emergencyPhone: '+91 98450 00005',
    notes: 'Graduated semester, completed clearance',
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2025-01-31T17:00:00Z',
  },
  {
    id: 'cand_6',
    candidateId: 'CAND-006',
    fullName: 'Karthik Nair',
    phoneNumber: '+91 98950 44556',
    email: 'karthik.n@example.com',
    address: 'Room 208, Narmada Hostel',
    joiningDate: '2025-02-15',
    monthlyRate: 3500,
    status: 'ACTIVE',
    emergencyContact: 'Sudha Nair (Mother)',
    emergencyPhone: '+91 98950 00006',
    notes: 'Evening tea & snacks package',
    createdAt: '2025-02-15T12:00:00Z',
    updatedAt: '2025-02-15T12:00:00Z',
  }
];

// Seed Attendance for Today
export let attendances: Attendance[] = [
  {
    id: 'att_1',
    candidateId: 'cand_1',
    attendanceDate: todayStr,
    status: 'IN',
    inTime: '07:30 AM',
    remarks: 'Breakfast present',
    createdAt: `${todayStr}T07:30:00Z`,
    updatedAt: `${todayStr}T07:30:00Z`,
  },
  {
    id: 'att_2',
    candidateId: 'cand_2',
    attendanceDate: todayStr,
    status: 'IN',
    inTime: '08:00 AM',
    remarks: 'Regular attendance',
    createdAt: `${todayStr}T08:00:00Z`,
    updatedAt: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'att_3',
    candidateId: 'cand_3',
    attendanceDate: todayStr,
    status: 'IN',
    inTime: '07:45 AM',
    remarks: 'On time',
    createdAt: `${todayStr}T07:45:00Z`,
    updatedAt: `${todayStr}T07:45:00Z`,
  },
  {
    id: 'att_4',
    candidateId: 'cand_4',
    attendanceDate: todayStr,
    status: 'IN',
    inTime: '07:15 AM',
    remarks: 'Early breakfast',
    createdAt: `${todayStr}T07:15:00Z`,
    updatedAt: `${todayStr}T07:15:00Z`,
  },
  {
    id: 'att_5',
    candidateId: 'cand_6',
    attendanceDate: todayStr,
    status: 'ABSENT',
    remarks: 'Internship visit',
    createdAt: `${todayStr}T09:00:00Z`,
    updatedAt: `${todayStr}T09:00:00Z`,
  }
];

// Seed Meals
export let meals: Meal[] = [
  {
    id: 'meal_1',
    candidateId: 'cand_1',
    mealDate: todayStr,
    mealType: 'BREAKFAST',
    isTaken: true,
    mealPreference: 'VEG',
    remarks: 'Idli & Sambar',
    createdAt: `${todayStr}T08:10:00Z`,
  },
  {
    id: 'meal_2',
    candidateId: 'cand_2',
    mealDate: todayStr,
    mealType: 'BREAKFAST',
    isTaken: true,
    mealPreference: 'VEG',
    remarks: 'Poha & Chai',
    createdAt: `${todayStr}T08:15:00Z`,
  },
  {
    id: 'meal_3',
    candidateId: 'cand_3',
    mealDate: todayStr,
    mealType: 'BREAKFAST',
    isTaken: true,
    mealPreference: 'VEG',
    remarks: 'Idli & Chutney',
    createdAt: `${todayStr}T08:20:00Z`,
  },
  {
    id: 'meal_4',
    candidateId: 'cand_4',
    mealDate: todayStr,
    mealType: 'BREAKFAST',
    isTaken: true,
    mealPreference: 'NON_VEG',
    remarks: 'Boiled Eggs & Bread Butter',
    createdAt: `${todayStr}T08:25:00Z`,
  },
  {
    id: 'meal_5',
    candidateId: 'cand_6',
    mealDate: todayStr,
    mealType: 'BREAKFAST',
    isTaken: false,
    mealPreference: 'VEG',
    remarks: 'Absent',
    createdAt: `${todayStr}T09:00:00Z`,
  },
  {
    id: 'meal_6',
    candidateId: 'cand_1',
    mealDate: todayStr,
    mealType: 'LUNCH',
    isTaken: true,
    mealPreference: 'VEG',
    remarks: 'Paneer Butter Masala, Roti, Rice, Dal',
    createdAt: `${todayStr}T13:10:00Z`,
  },
  {
    id: 'meal_7',
    candidateId: 'cand_2',
    mealDate: todayStr,
    mealType: 'LUNCH',
    isTaken: true,
    mealPreference: 'VEG',
    remarks: 'Thali lunch',
    createdAt: `${todayStr}T13:20:00Z`,
  }
];

// Seed Expenses
export let expenses: Expense[] = [
  {
    id: 'exp_1',
    itemName: 'Fresh Farm Cow Milk',
    quantity: 60,
    unit: 'Litre',
    rate: 55,
    category: 'Dairy',
    subCategory: 'Milk & Paneer',
    vendorName: 'Amrit Dairy Farm',
    vendorPhone: '+91 94111 22334',
    invoiceNumber: 'INV-2025-081',
    expenseDate: todayStr,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    remarks: 'Daily morning & tea supply',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T07:00:00Z`,
  },
  {
    id: 'exp_2',
    itemName: 'Basmati Rice Premium (50kg bag)',
    quantity: 4,
    unit: 'Bag',
    rate: 3200,
    category: 'Groceries',
    subCategory: 'Grains & Pulses',
    vendorName: 'Shree Krishna Traders',
    vendorPhone: '+91 94222 33445',
    invoiceNumber: 'INV-2025-079',
    expenseDate: todayStr,
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'PAID',
    remarks: 'Fortnightly stock replenishment',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T09:30:00Z`,
  },
  {
    id: 'exp_3',
    itemName: 'Fresh Seasonal Vegetables (Onion, Potato, Tomato, Palak)',
    quantity: 85,
    unit: 'Kg',
    rate: 42,
    category: 'Vegetables',
    subCategory: 'Mandi Produce',
    vendorName: 'Subzi Mandi Wholesale #4',
    vendorPhone: '+91 94333 44556',
    invoiceNumber: 'MANDI-1044',
    expenseDate: todayStr,
    paymentMethod: 'CASH',
    paymentStatus: 'PAID',
    remarks: 'Mandi fresh pick for lunch & dinner',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T06:30:00Z`,
  },
  {
    id: 'exp_4',
    itemName: 'Commercial LPG Cylinder (19kg)',
    quantity: 3,
    unit: 'Cylinder',
    rate: 1850,
    category: 'Gas & Fuel',
    subCategory: 'Kitchen Gas',
    vendorName: 'Bharat Gas Agency',
    vendorPhone: '+91 94444 55667',
    invoiceNumber: 'BHP-88912',
    expenseDate: '2025-02-28',
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    remarks: 'Monthly kitchen refuel',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-28T14:00:00Z',
  },
  {
    id: 'exp_5',
    itemName: 'Cooking Mustard Oil (15L Tin)',
    quantity: 3,
    unit: 'Tin',
    rate: 1950,
    category: 'Groceries',
    subCategory: 'Oils & Spices',
    vendorName: 'Shree Krishna Traders',
    vendorPhone: '+91 94222 33445',
    invoiceNumber: 'INV-2025-080',
    expenseDate: '2025-02-27',
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    remarks: 'Kitchen deep fry and cooking',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-27T11:00:00Z',
  }
];

// Seed Stock Items
export let stockItems: StockItem[] = [
  {
    id: 'stock_1',
    itemName: 'Basmati Rice Premium (50kg bag)',
    category: 'Grains',
    subCategory: 'Rice',
    unit: 'Bag',
    currentStock: 5,
    minimumStockLevel: 3,
    maximumStockLevel: 15,
    unitPrice: 3200,
    description: 'Long grain aromatic rice for lunch and dinners',
    supplierName: 'Shree Krishna Traders',
    supplierContact: '+91 94222 33445',
    status: 'ACTIVE',
    enteredByCandidateId: 'cand_1',
    primaryImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=60'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: todayStr,
  },
  {
    id: 'stock_2',
    itemName: 'Toor Dal (Arhar Dal)',
    category: 'Pulses',
    subCategory: 'Lentils',
    unit: 'Kg',
    currentStock: 18,
    minimumStockLevel: 25, // Low stock!
    maximumStockLevel: 80,
    unitPrice: 155,
    description: 'Grade A polished toor dal for daily sambar and tadka',
    supplierName: 'Shree Krishna Traders',
    supplierContact: '+91 94222 33445',
    status: 'ACTIVE',
    enteredByCandidateId: 'cand_1',
    primaryImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&auto=format&fit=crop&q=60'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: todayStr,
  },
  {
    id: 'stock_3',
    itemName: 'Chakki Fresh Whole Wheat Atta',
    category: 'Flour',
    subCategory: 'Atta',
    unit: 'Kg',
    currentStock: 90,
    minimumStockLevel: 40,
    maximumStockLevel: 200,
    unitPrice: 42,
    description: '100% whole wheat stone ground flour for rotis and puris',
    supplierName: 'Kisan Agro Flour Mill',
    supplierContact: '+91 94555 66778',
    status: 'ACTIVE',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: todayStr,
  },
  {
    id: 'stock_4',
    itemName: 'Refined Sunflower Cooking Oil',
    category: 'Oils',
    subCategory: 'Edible Oils',
    unit: 'Litre',
    currentStock: 12,
    minimumStockLevel: 20, // Low stock!
    maximumStockLevel: 60,
    unitPrice: 140,
    description: 'Fortune sunlite edible refined oil',
    supplierName: 'Shree Krishna Traders',
    supplierContact: '+91 94222 33445',
    status: 'ACTIVE',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: todayStr,
  },
  {
    id: 'stock_5',
    itemName: 'Fresh Malai Paneer',
    category: 'Dairy',
    subCategory: 'Paneer',
    unit: 'Kg',
    currentStock: 6,
    minimumStockLevel: 5,
    maximumStockLevel: 25,
    unitPrice: 380,
    description: 'Fresh cow & buffalo milk cottage cheese',
    supplierName: 'Amrit Dairy Farm',
    supplierContact: '+91 94111 22334',
    status: 'ACTIVE',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: todayStr,
  }
];

// Seed Stock Transactions
export let stockTransactions: StockTransaction[] = [
  {
    id: 'stx_1',
    stockItemId: 'stock_1',
    transactionType: 'PURCHASE',
    quantity: 4,
    unitPrice: 3200,
    transactionDate: todayStr,
    referenceNumber: 'INV-2025-079',
    referenceType: 'PO',
    remarks: 'Received 4 bags',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T09:30:00Z`,
  },
  {
    id: 'stx_2',
    stockItemId: 'stock_2',
    transactionType: 'USAGE',
    quantity: 8,
    unitPrice: 155,
    transactionDate: todayStr,
    remarks: 'Used for lunch dal preparation',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T11:00:00Z`,
  },
  {
    id: 'stx_3',
    stockItemId: 'stock_3',
    transactionType: 'USAGE',
    quantity: 15,
    unitPrice: 42,
    transactionDate: todayStr,
    remarks: 'Roti dough for 80 candidates',
    enteredByCandidateId: 'cand_1',
    createdAt: `${todayStr}T11:30:00Z`,
  }
];

// Seed Staff
export let staffList: Staff[] = [
  {
    id: 'staff_1',
    staffId: 'STF-01',
    fullName: 'Rameshwar Lal (Head Chef)',
    position: 'Head Chef',
    phoneNumber: '+91 91234 56780',
    email: 'rameshwar.chef@gmail.com',
    address: 'Near Old Bus Stand, Civil Lines',
    joiningDate: '2023-04-01',
    baseSalary: 24000,
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    emergencyContact: 'Sunita Lal (Wife)',
    emergencyPhone: '+91 91234 50001',
    bankName: 'State Bank of India',
    bankAccountNumber: '30998877665',
    ifscCode: 'SBIN0001234',
    enteredByCandidateId: 'cand_1',
    createdAt: '2023-04-01T09:00:00Z',
    updatedAt: '2023-04-01T09:00:00Z',
  },
  {
    id: 'staff_2',
    staffId: 'STF-02',
    fullName: 'Mohan Kumar (Assistant Cook)',
    position: 'Assistant Cook',
    phoneNumber: '+91 91345 67891',
    email: 'mohan.kumar@gmail.com',
    address: 'Shanti Nagar, Sector 4',
    joiningDate: '2023-08-15',
    baseSalary: 16000,
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    emergencyContact: 'Kishore Kumar (Brother)',
    emergencyPhone: '+91 91345 60002',
    bankName: 'Punjab National Bank',
    bankAccountNumber: '44556677889',
    ifscCode: 'PUNB0123456',
    enteredByCandidateId: 'cand_1',
    createdAt: '2023-08-15T09:00:00Z',
    updatedAt: '2023-08-15T09:00:00Z',
  },
  {
    id: 'staff_3',
    staffId: 'STF-03',
    fullName: 'Dinesh Yadav (Mess Helper & Cleaning)',
    position: 'Mess Helper',
    phoneNumber: '+91 91456 78902',
    address: 'Railway Colony, Gate #2',
    joiningDate: '2024-01-10',
    baseSalary: 12000,
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    emergencyContact: 'Sarita Yadav (Wife)',
    emergencyPhone: '+91 91456 70003',
    bankName: 'HDFC Bank',
    bankAccountNumber: '50100223344',
    ifscCode: 'HDFC0002345',
    enteredByCandidateId: 'cand_1',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-10T09:00:00Z',
  }
];

// Seed Staff Payments
export let staffPayments: StaffPayment[] = [
  {
    id: 'spay_1',
    staffId: 'staff_1',
    paymentDate: '2025-02-05',
    amount: 24000,
    paymentMonth: 'January',
    paymentYear: 2025,
    paymentMonthNumber: 1,
    bonus: 1000,
    deductions: 0,
    paymentMethod: 'BANK_TRANSFER',
    transactionId: 'TXN-SAL-JAN-01',
    remarks: 'January salary paid in full',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-05T10:00:00Z',
  },
  {
    id: 'spay_2',
    staffId: 'staff_2',
    paymentDate: '2025-02-05',
    amount: 16000,
    paymentMonth: 'January',
    paymentYear: 2025,
    paymentMonthNumber: 1,
    paymentMethod: 'BANK_TRANSFER',
    transactionId: 'TXN-SAL-JAN-02',
    remarks: 'January salary paid',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-05T10:05:00Z',
  },
  {
    id: 'spay_3',
    staffId: 'staff_3',
    paymentDate: '2025-02-05',
    amount: 12000,
    paymentMonth: 'January',
    paymentYear: 2025,
    paymentMonthNumber: 1,
    paymentMethod: 'CASH',
    remarks: 'January salary paid in cash',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-05T10:10:00Z',
  }
];

// Seed Staff Advances
export let staffAdvances: StaffAdvance[] = [
  {
    id: 'sadv_1',
    staffId: 'staff_2',
    advanceDate: '2025-02-10',
    amount: 5000,
    reason: 'Medical checkup for mother',
    installmentMonths: 2,
    monthlyDeduction: 2500,
    status: 'APPROVED',
    approvedByCandidateId: 'cand_1',
    approvedAt: '2025-02-10T14:00:00Z',
    repaidAmount: 2500,
    remainingAmount: 2500,
    remarks: 'First installment deducted from Feb cycle',
    enteredByCandidateId: 'cand_1',
    createdAt: '2025-02-10T11:00:00Z',
  }
];

// Seed Fee Collections
export let feeCollections: FeeCollection[] = [
  {
    id: 'fee_1',
    candidateId: 'cand_1',
    collectionDate: `${currentYear}-02-02`,
    amount: 3500,
    paymentMonth: 'February',
    paymentYear: currentYear,
    paymentMonthNumber: 2,
    paymentMethod: 'UPI',
    transactionId: 'UPI-FEE-40918',
    remarks: 'February mess subscription paid',
    collectedByCandidateId: 'cand_1',
    createdAt: `${currentYear}-02-02T10:00:00Z`,
  },
  {
    id: 'fee_2',
    candidateId: 'cand_2',
    collectionDate: `${currentYear}-02-03`,
    amount: 3500,
    paymentMonth: 'February',
    paymentYear: currentYear,
    paymentMonthNumber: 2,
    paymentMethod: 'BANK_TRANSFER',
    transactionId: 'NEFT-889922',
    remarks: 'February fees cleared',
    collectedByCandidateId: 'cand_1',
    createdAt: `${currentYear}-02-03T11:30:00Z`,
  },
  {
    id: 'fee_3',
    candidateId: 'cand_3',
    collectionDate: `${currentYear}-02-04`,
    amount: 3500,
    paymentMonth: 'February',
    paymentYear: currentYear,
    paymentMonthNumber: 2,
    paymentMethod: 'UPI',
    transactionId: 'UPI-FEE-99104',
    remarks: 'Paid via GPay',
    collectedByCandidateId: 'cand_1',
    createdAt: `${currentYear}-02-04T12:00:00Z`,
  },
  {
    id: 'fee_4',
    candidateId: 'cand_4',
    collectionDate: `${currentYear}-02-01`,
    amount: 3800,
    paymentMonth: 'February',
    paymentYear: currentYear,
    paymentMonthNumber: 2,
    paymentMethod: 'CASH',
    remarks: 'Monthly rate + gym diet addon',
    collectedByCandidateId: 'cand_1',
    createdAt: `${currentYear}-02-01T09:00:00Z`,
  }
];

// Seed Parties / Catering Bookings
export let parties: Party[] = [
  {
    id: 'party_1',
    partyId: 'PTY-2025-01',
    partyName: 'Robotics Club Annual Dinner',
    contactPerson: 'Aditya Sen (Club President)',
    phoneNumber: '+91 99112 23344',
    email: 'robotics.club@campus.edu',
    address: 'Campus Auditorium Lawn',
    eventDate: '2025-03-15',
    numberOfPeople: 65,
    mealType: 'BOTH',
    thaliRate: 280,
    discount: 500,
    discountType: 'FIXED',
    paymentStatus: 'PARTIAL',
    paidAmount: 8000,
    paymentMethod: 'UPI',
    specialRequests: 'Live Gulab Jamun stall, Butter Chicken & Shahi Paneer counter',
    remarks: 'Advance paid; balance payable post dinner',
    enteredByCandidateId: 'cand_1',
    extraItems: [
      { itemName: 'Ice Cream Cup (Vanilla & Chocolate)', quantity: 65, rate: 25, unit: 'Cup' },
      { itemName: 'Welcome Drink (Masala Chaas)', quantity: 65, rate: 20, unit: 'Glass' }
    ],
    invoiceNumber: 'INV-PARTY-001',
    createdAt: '2025-02-20T10:00:00Z',
    updatedAt: '2025-02-20T10:00:00Z',
  },
  {
    id: 'party_2',
    partyId: 'PTY-2025-02',
    partyName: 'Prof. Verma Farewell High Tea & Dinner',
    contactPerson: 'Dr. S. K. Gupta',
    phoneNumber: '+91 98112 34567',
    email: 'skgupta@dept.edu',
    address: 'Faculty Guest House Lounge',
    eventDate: '2025-03-22',
    numberOfPeople: 40,
    mealType: 'VEG',
    thaliRate: 320,
    paymentStatus: 'PAID',
    paidAmount: 12800,
    paymentMethod: 'BANK_TRANSFER',
    specialRequests: 'Special Rajasthani Dal Baati Churma Thali',
    remarks: 'Payment cleared in advance via Department account',
    enteredByCandidateId: 'cand_1',
    invoiceNumber: 'INV-PARTY-002',
    createdAt: '2025-02-25T14:00:00Z',
    updatedAt: '2025-02-25T14:00:00Z',
  }
];

// Seed Menus
export let menus: Menu[] = [
  {
    id: 'menu_1',
    menuDate: todayStr,
    mealType: 'BREAKFAST',
    menuName: 'South Indian Breakfast Feast',
    description: 'Hot steamed Idlis, Crispy Medu Vada, Coconut Chutney, Tomato Chutney, & Piping Hot Drumstick Sambar',
    isSpecial: false,
    status: 'ACTIVE',
    createdByCandidateId: 'cand_1',
    items: [
      { id: 'item_1', itemName: 'Steamed Rava Idli', price: 30, category: 'Main', isVegetarian: true, isAvailable: true },
      { id: 'item_2', itemName: 'Crispy Medu Vada', price: 25, category: 'Snack', isVegetarian: true, isAvailable: true },
      { id: 'item_3', itemName: 'Traditional Sambar', price: 15, category: 'Curry', isVegetarian: true, isAvailable: true },
      { id: 'item_4', itemName: 'Ginger Masala Tea', price: 10, category: 'Beverage', isVegetarian: true, isAvailable: true }
    ],
    createdAt: `${todayStr}T06:00:00Z`,
  },
  {
    id: 'menu_2',
    menuDate: todayStr,
    mealType: 'LUNCH',
    menuName: 'North Indian Deluxe Thali',
    description: 'Fresh Paneer Butter Masala, Dhaba Style Dal Tadka, Jeera Rice, Tawa Phulkas, Boondi Raita, Salad & Papad',
    isSpecial: true,
    specialRemarks: 'Paneer special day',
    status: 'ACTIVE',
    createdByCandidateId: 'cand_1',
    items: [
      { id: 'item_5', itemName: 'Paneer Butter Masala', price: 90, category: 'Gravy', isVegetarian: true, isAvailable: true },
      { id: 'item_6', itemName: 'Yellow Dal Tadka', price: 50, category: 'Dal', isVegetarian: true, isAvailable: true },
      { id: 'item_7', itemName: 'Desi Ghee Phulka (Roti)', price: 8, category: 'Breads', isVegetarian: true, isAvailable: true },
      { id: 'item_8', itemName: 'Fragrant Jeera Rice', price: 40, category: 'Rice', isVegetarian: true, isAvailable: true },
      { id: 'item_9', itemName: 'Boondi Raita', price: 20, category: 'Sides', isVegetarian: true, isAvailable: true }
    ],
    createdAt: `${todayStr}T06:00:00Z`,
  },
  {
    id: 'menu_3',
    menuDate: todayStr,
    mealType: 'DINNER',
    menuName: 'Healthy Homestyle Dinner',
    description: 'Aloo Gobi Matar, Mix Veg Khichdi / Steamed Rice, Masoor Dal, Soft Chapatis, Gulab Jamun',
    isSpecial: false,
    status: 'ACTIVE',
    createdByCandidateId: 'cand_1',
    items: [
      { id: 'item_10', itemName: 'Aloo Gobi Matar Sabzi', price: 60, category: 'Sabzi', isVegetarian: true, isAvailable: true },
      { id: 'item_11', itemName: 'Masoor Dal Tadka', price: 45, category: 'Dal', isVegetarian: true, isAvailable: true },
      { id: 'item_12', itemName: 'Wheat Chapatis', price: 8, category: 'Breads', isVegetarian: true, isAvailable: true },
      { id: 'item_13', itemName: 'Hot Gulab Jamun (2 pcs)', price: 30, category: 'Dessert', isVegetarian: true, isAvailable: true }
    ],
    createdAt: `${todayStr}T06:00:00Z`,
  }
];
