# Tailwind palette (v3/v4 shared values) for the hues actually used in this codebase
PALETTE = {
    'slate':   {50:'#f8fafc',100:'#f1f5f9',200:'#e2e8f0',300:'#cbd5e1',400:'#94a3b8',500:'#64748b',600:'#475569',700:'#334155',800:'#1e293b',900:'#0f172a',950:'#020617'},
    'blue':    {50:'#eff6ff',100:'#dbeafe',200:'#bfdbfe',300:'#93c5fd',400:'#60a5fa',500:'#3b82f6',600:'#2563eb',700:'#1d4ed8',800:'#1e40af',900:'#1e3a8a',950:'#172554'},
    'rose':    {50:'#fff1f2',100:'#ffe4e6',200:'#fecdd3',300:'#fda4af',400:'#fb7185',500:'#f43f5e',600:'#e11d48',700:'#be123c',800:'#9f1239',900:'#881337',950:'#4c0519'},
    'amber':   {50:'#fffbeb',100:'#fef3c7',200:'#fde68a',300:'#fcd34d',400:'#fbbf24',500:'#f59e0b',600:'#d97706',700:'#b45309',800:'#92400e',900:'#78350f',950:'#451a03'},
    'emerald': {50:'#ecfdf5',100:'#d1fae5',200:'#a7f3d0',300:'#6ee7b7',400:'#34d399',500:'#10b981',600:'#059669',700:'#047857',800:'#065f46',900:'#064e3b',950:'#022c22'},
    'green':   {50:'#f0fdf4',100:'#dcfce7',200:'#bbf7d0',300:'#86efac',400:'#4ade80',500:'#22c55e',600:'#16a34a',700:'#15803d',800:'#166534',900:'#14532d',950:'#052e16'},
    'red':     {50:'#fef2f2',100:'#fee2e2',200:'#fecaca',300:'#fca5a5',400:'#f87171',500:'#ef4444',600:'#dc2626',700:'#b91c1c',800:'#991b1b',900:'#7f1d1d',950:'#450a0a'},
    'indigo':  {50:'#eef2ff',100:'#e0e7ff',200:'#c7d2fe',300:'#a5b4fc',400:'#818cf8',500:'#6366f1',600:'#4f46e5',700:'#4338ca',800:'#3730a3',900:'#312e81',950:'#1e1b4b'},
}

rules = []

def esc(cls):
    return cls.replace(':', r'\:').replace('/', r'\/').replace('.', r'\.')

def add(cls, prop, value):
    rules.append((f'.dark .{esc(cls)}', prop, value))

neutral_bg = {
    'bg-white': 800, 'bg-slate-50': 900, 'bg-slate-100': 800, 'bg-slate-200': 700,
    'bg-slate-400': 600, 'bg-slate-800': 200, 'bg-slate-900': 600, 'bg-slate-950': 700,
    'hover:bg-slate-50': 800, 'hover:bg-slate-100': 700, 'hover:bg-slate-200': 600,
    'hover:bg-slate-300': 500, 'hover:bg-slate-800': 500,
}
for cls, shade in neutral_bg.items():
    add(cls, 'background-color', PALETTE['slate'][shade])

neutral_text = {
    'text-slate-950': 50, 'text-slate-900': 100, 'text-slate-800': 200, 'text-slate-700': 300,
    'text-slate-600': 400, 'text-slate-500': 400, 'text-slate-400': 500,
    'hover:text-slate-600': 300, 'hover:text-slate-700': 200, 'hover:text-slate-800': 100,
    'hover:text-slate-900': 50,
}
for cls, shade in neutral_text.items():
    add(cls, 'color', PALETTE['slate'][shade])

neutral_border = {
    'border-slate-100': 800, 'border-slate-200': 700, 'border-slate-300': 600,
    'divide-slate-100': 800, 'hover:border-slate-300': 500,
}
for cls, shade in neutral_border.items():
    add(cls, 'border-color', PALETTE['slate'][shade])

gray_text = {'text-gray-900':100,'text-gray-700':300,'text-gray-600':400,'text-gray-500':400,'text-gray-400':500,
             'hover:text-gray-900':50,'hover:text-gray-700':200,'hover:text-gray-600':300}
for cls, shade in gray_text.items():
    add(cls, 'color', PALETTE['slate'][shade])
add('border-gray-300', 'border-color', PALETTE['slate'][600])

ACCENTS = ['blue','rose','amber','emerald','green','red','indigo']
for c in ACCENTS:
    p = PALETTE[c]
    add(f'bg-{c}-50', 'background-color', p[950])
    add(f'bg-{c}-100', 'background-color', p[900])
    add(f'hover:bg-{c}-50', 'background-color', p[900])
    add(f'hover:bg-{c}-100', 'background-color', p[800])
    add(f'hover:bg-{c}-200', 'background-color', p[700])

    for shade, target in [(500,400),(600,400),(700,300),(800,300),(900,200)]:
        add(f'text-{c}-{shade}', 'color', p[target])
    add(f'hover:text-{c}-600', 'color', p[300])
    add(f'hover:text-{c}-700', 'color', p[200])
    add(f'hover:text-{c}-800', 'color', p[200])

    add(f'border-{c}-100', 'border-color', p[800])
    add(f'border-{c}-200', 'border-color', p[700])
    add(f'border-{c}-300', 'border-color', p[600])
    add(f'border-{c}-400', 'border-color', p[600])

for c in ['blue','indigo']:
    p = PALETTE[c]
    add(f'from-{c}-50', 'background-color', p[950])
    add(f'to-{c}-100', 'background-color', p[900])

seen = {}
for sel, prop, val in rules:
    seen[(sel, prop)] = val

lines = []
lines.append('/* ===================================================================')
lines.append('   Dark mode overrides (generated by scripts/gen_dark_css.py)')
lines.append('   Existing light-mode Tailwind utility classes are remapped to')
lines.append('   dark-appropriate colors whenever a `.dark` ancestor class is present')
lines.append('   (see ThemeProvider in src/theme.tsx). These rules intentionally sit')
lines.append('   outside any Tailwind @layer, so per CSS cascade-layer semantics they')
lines.append('   win over Tailwind\'s layered utility classes unconditionally, no')
lines.append('   !important needed.')
lines.append('   =================================================================== */')
lines.append('.dark { color-scheme: dark; }')
lines.append('')

by_selector = {}
for (sel, prop), val in seen.items():
    by_selector.setdefault(sel, []).append((prop, val))

for sel in sorted(by_selector.keys()):
    decls = by_selector[sel]
    decl_str = ' '.join(f'{p}: {v};' for p, v in decls)
    lines.append(f'{sel} {{ {decl_str} }}')

out_path = 'S:/work/MessMap-main/MessMap-main/frontend/src/dark-overrides.css'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print('rules:', len(by_selector))
